[supervisord]

nodaemon=true

logfile=/dev/null

pidfile=/tmp/supervisord.pid



[program:singbox]

command=/usr/local/bin/sing-box run -c /app/config/config.json


directory=/app


autostart=true

autorestart=true


startsecs=1


stdout_logfile=/dev/stdout

stdout_logfile_maxbytes=0


stderr_logfile=/dev/stderr

stderr_logfile_maxbytes=0



[program:cloudflared]

command=/bin/sh -c '/usr/local/bin/cloudflared tunnel run --token ${TUNNEL_TOKEN}'


autostart=false

autorestart=false


stdout_logfile=/dev/stdout

stdout_logfile_maxbytes=0


stderr_logfile=/dev/stderr

stderr_logfile_maxbytes=0
